version: '2'
template:
  name: "Clause Perishable Goods Demo"
  description: "The Delivery Pipeline automates the continuous deployment of the IBM Blockchain Starter Kit to IBM Cloud.\nDeployment of this toolchain should take about 10 minutes. While you are waiting you can get started with [setting up your Smart Legal Contract on Clause](https://hub.clause.io/open-signup?help=48)."
  required:
    - build
    - repo
    - deploy

toolchain:
  name: 'clause-perishable-{{timestamp}}'

services:
  repo:
    service_id: githubpublic
    parameters:
      repo_name: 'demo-clause-ibm-perishable-goods'
      repo_url: 'https://github.com/clauseHQ/demo-clause-ibm-perishable-goods'
      type: fork
      has_issues: true
      enable_traceability: true
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      ui-pipeline: true
      sin: 'test'
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
          SPACE_NAME: '{{form.pipeline.parameters.deploy-space}}'
          ORG_NAME: '{{form.pipeline.parameters.deploy-organization}}'
          REGION_ID: '{{form.pipeline.parameters.deploy-region}}'
        execute: true

form:
  pipeline:
    parameters:
      deploy-region: 'ibm:yp:us-south'
    schema:
      $ref: deploy.json
