version: '2'
template:
  name: "Clause Perishable Goods Demo"
  description: "Deploy the Clause Perishable Goods Demo for IBM Blockchain Platform to IBM Cloud."
  required:
    - build
    - repo
    - deploy

toolchain:
  name: 'demo-clause-ibm-perishable-goods-{{timestamp}}'

services:
  repo:
    service_id: githubpublic
    parameters:
      repo_name: 'demo-clause-ibm-perishable-goods'
      repo_url: 'https://github.com/clauseHQ/demo-clause-ibm-perishable-goods'
      type: clone
      has_issues: true
      enable_traceability: true
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
          SPACE_NAME: '{{form.pipeline.parameters.deploy-space}}'
          ORG_NAME: '{{form.pipeline.parameters.deploy-organization}}'
          REGION_ID: '{{form.pipeline.parameters.deploy-region}}'
        execute: true

form:
  pipeline:
    parameters:
      deploy-region: 'ibm:yp:us-south'
    schema:
      $ref: deploy.json
